### ISSUE TITLE
Export action doesn't work

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-datatools#2]
- create some entity browser (or use User browser)
- add export action to the table (with Studio's component inspector)
- run application and try to use Export button

Exception occurs:
```
java.lang.NullPointerException
	at io.jmix.datatoolsui.action.ExportAction.actionPerform(ExportAction.java:112)
	at io.jmix.ui.component.impl.WebButton.buttonClicked(WebButton.java:65)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by gorbunkov** [comment]
io.jmix.datatoolsui.action.ExportAction doesn't exist any more, the io.jmix.uiexport.action.ExportAction is not available for adding by studio component inspector (the ExportAction is a base action for other actions and should not be used directly)
